image: php:7.1.9-apache

stages:
  - build
  - deploy

dependency_installs:
  stage: build
  script:
    - composer install

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - echo "Deploying master to staging"
    - echo $GREETING

deploy_production:
  stage: deploy
  environment: production
  only:
    - tags
  script:
    - docker-compose build
    - docker-compose push
    - echo "Deploying tag to production"
    - echo $GREETING
